### ISSUE TITLE
root_path non utilizza il percorso assoluto assegnato

### ISSUE THREAD

**Issue by Craffo** [AstraeLabs/VibraVid#209]
Sto riscontrando un problema con la configurazione del parametro `root_path`. Quando imposto il valore come segue:

`"root_path": "Z:\\StreamingDownload\\Downloads"`

lo script non utilizza il percorso assegnato. Invece, crea il percorso \StreamingDownload\Downloads nella stessa directory in cui si trova lo script.

Mi aspetto che lo script utilizzi direttamente il percorso assoluto specificato, salvando i file nella directory corretta (Z:\StreamingDownload\Downloads), senza creare sottocartelle nella directory dello script.

**Comment by Arrowar** [comment]
Nei prossimi giorni controllo e porto il fix.

**Comment by Arrowar** [comment]
Ho appena provato e sembra funzionare che versione stai usando ?

**Comment by Craffo** [comment]
La versione più recente, ho usato `./ update.py` proprio ieri...
Ho anche provato più e più volte a controllare che la formattazione del percorso fosse corretta...
E ho anche provato a reinstallare lo script, ma non risolve il problema

**Comment by Arrowar** [comment]
Strano io ho fatto partire lo script da c e gli ho detto di scaricare in D:\\Video e mette tutto dentro d:\video.

**Comment by Craffo** [comment]
Quindi in config.json devo trovare seguente:

"root_path": "D:\\Video"

E poi in teoria dovrei trovare una cartella sul disco D chiamata Video, ma non è il caso perché finisce sempre per crearmi la cartella/il percorso specificato all'interno della cartella dove si trova test_run.py

**Comment by Arrowar** [comment]
D:\\\\ altrimenti dovrebbe dare problemi

**Comment by Craffo** [comment]
**Ho trovato il problema**, per qualche motivo lo script sembra non amare il fatto che il mio disco rigido dove voglio salvare i file scaricati, si chiami `Z:\`, utilizzando un disco rigido con una qualsiasi altra lettera, il problema si risolve.

EDIT: Il problema persiste anche dopo aver cambiato la lettera assegnata al disco in questione, allora a questo punto l'ultima ipotesi che mi resta è che si tratta di una partizione estesa (Spanned Volume) e sia questo a creare problemi

**Comment by Samue1e** [comment]
Ho avuto anch'io quel problema, è dovuto ad os.path.join nelle funzioni sanitize di [os.py](https://github.com/Lovi-0/StreamingCommunity/blob/main/StreamingCommunity/Util/os.py) che su windows ha un comportamento non proprio intuitivo.
Dalla documentazione:
On Windows, the drive is not reset when a rooted path segment (e.g., '\foo') is encountered. If a segment is on a different drive or is an absolute path, all previous segments are ignored and the drive is reset. Note that since there is a current directory for each drive, os.path.join("c:", "foo") represents a path relative to the current directory on drive C: (c:foo), not c:\foo.

Quindi se ho capito bene Z:\\StreamingDownload\\Downloads viene convertito in Z:StreamingDownload\\Downloads che non è più un path assoluto ma relativo alla cartella in cui ti trovi, da cui l'errore. Una soluzione sarebbe tipo
`path = os.path.join('c:', os.sep, 'dir')`, ma dovresti controllare di essere su windows e che il path originale sia un path assoluto.

**Comment by Arrowar** [comment]
Porto il fix con la nuova versione
